package com.teleframe.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * ITSMonitorEndpointService service = new ITSMonitorEndpointService();
 * ITSMonitorEndpoint portType = service.getITSMonitorEndpoinInstance();
 * portType.getWarning(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "ITSMonitorEndpointService", targetNamespace = "http://webservice.teleframe.com", wsdlLocation = "http://10.168.1.110/TeleframeService/service/ITSMonitorEndpointService?wsdl")
public class ITSMonitorEndpointService extends Service {

	private final static URL ITSMONITORENDPOINTSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.teleframe.webservice.ITSMonitorEndpointService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.teleframe.webservice.ITSMonitorEndpointService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://10.168.1.110/TeleframeService/service/ITSMonitorEndpointService?wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://10.168.1.110/TeleframeService/service/ITSMonitorEndpointService?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		ITSMONITORENDPOINTSERVICE_WSDL_LOCATION = url;
	}

	public ITSMonitorEndpointService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public ITSMonitorEndpointService() {
		super(ITSMONITORENDPOINTSERVICE_WSDL_LOCATION, new QName(
				"http://webservice.teleframe.com", "ITSMonitorEndpointService"));
	}

	/**
	 * 
	 * @return returns ITSMonitorEndpoint
	 */
	@WebEndpoint(name = "ITSMonitorEndpoinInstance")
	public ITSMonitorEndpoint getITSMonitorEndpoinInstance() {
		return super.getPort(new QName("http://webservice.teleframe.com",
				"ITSMonitorEndpoinInstance"), ITSMonitorEndpoint.class);
	}

}
