package com.teleframe.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ITSMonitorEndpoint", targetNamespace = "http://webservice.teleframe.com")
@SOAPBinding(style = SOAPBinding.Style.RPC)
public interface ITSMonitorEndpoint {

	/**
	 * 
	 * @param dir
	 * @param ssid
	 * @param reqLines
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(partName = "return")
	public String getWarning(
			@WebParam(name = "ssid", partName = "ssid") String ssid,
			@WebParam(name = "reqLines", partName = "reqLines") int reqLines,
			@WebParam(name = "dir", partName = "dir") int dir);

	/**
	 * 
	 * @param fromId
	 * @param dir
	 * @param ssid
	 * @param reqLines
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(partName = "return")
	public String getWarningInfo(
			@WebParam(name = "ssid", partName = "ssid") String ssid,
			@WebParam(name = "fromId", partName = "fromId") long fromId,
			@WebParam(name = "reqLines", partName = "reqLines") int reqLines,
			@WebParam(name = "dir", partName = "dir") int dir);

	/**
	 * 
	 * @param msgid
	 * @param ssid
	 * @return returns int
	 */
	@WebMethod(operationName = "Received")
	@WebResult(partName = "return")
	public int received(
			@WebParam(name = "ssid", partName = "ssid") String ssid,
			@WebParam(name = "msgid", partName = "msgid") long msgid);

	/**
	 * 
	 * @param fromId
	 * @param dir
	 * @param ssid
	 * @param reqLines
	 * @return returns java.lang.String
	 */
	@WebMethod
	@WebResult(partName = "return")
	public String getWarningFromId(
			@WebParam(name = "ssid", partName = "ssid") String ssid,
			@WebParam(name = "fromId", partName = "fromId") long fromId,
			@WebParam(name = "reqLines", partName = "reqLines") int reqLines,
			@WebParam(name = "dir", partName = "dir") int dir);

	/**
	 * 
	 * @param ssid
	 * @param msgids
	 * @return returns int
	 */
	@WebMethod(operationName = "Receiveds")
	@WebResult(partName = "return")
	public int receiveds(
			@WebParam(name = "ssid", partName = "ssid") String ssid,
			@WebParam(name = "msgids", partName = "msgids") String msgids);

}
