package com.teleframe.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * UserEndpointService service = new UserEndpointService();
 * UserEndpoint portType = service.getUserEndpoinInstance();
 * portType.checkUser(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "UserEndpointService", targetNamespace = "http://webservice.teleframe.com", wsdlLocation = "http://10.168.1.110/TeleframeService/service/UserEndpointService?wsdl")
public class UserEndpointService extends Service {

	private final static URL USERENDPOINTSERVICE_WSDL_LOCATION;
	private final static Logger logger = Logger
			.getLogger(com.teleframe.webservice.UserEndpointService.class
					.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = com.teleframe.webservice.UserEndpointService.class
					.getResource(".");
			url = new URL(baseUrl,
					"http://10.168.1.110/TeleframeService/service/UserEndpointService?wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://10.168.1.110/TeleframeService/service/UserEndpointService?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		USERENDPOINTSERVICE_WSDL_LOCATION = url;
	}

	public UserEndpointService(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public UserEndpointService() {
		super(USERENDPOINTSERVICE_WSDL_LOCATION, new QName(
				"http://webservice.teleframe.com", "UserEndpointService"));
	}

	/**
	 * 
	 * @return returns UserEndpoint
	 */
	@WebEndpoint(name = "UserEndpoinInstance")
	public UserEndpoint getUserEndpoinInstance() {
		return super.getPort(new QName("http://webservice.teleframe.com",
				"UserEndpoinInstance"), UserEndpoint.class);
	}

}
